# This file was generated by GoReleaser. DO NOT EDIT.
class BackyardsCli < Formula
  desc "Command-line interface for Backyards"
  homepage "https://banzaicloud.com/"
  version "1.5.5"
  bottle :unneeded

  if OS.mac?
    url "https://banzaicloud.com/downloads/backyards-cli/1.5.5/dist/backyards_1.5.5_darwin_amd64.tar.gz"
    sha256 "dc9544d732b7db7f8e0349e7f3f719741ff3e05a6d3452dae271a0edf55b53c1"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://banzaicloud.com/downloads/backyards-cli/1.5.5/dist/backyards_1.5.5_linux_amd64.tar.gz"
      sha256 "32cb6a0f56cca6a7ceb940bade9ec6225464bdee1e1340021e20ae24b2b626cb"
    end
  end

  def install
    bin.install "backyards"
  end

  test do
    system "#{bin}/backyards --version"
  end
end
