# This file was generated by GoReleaser. DO NOT EDIT.
class BackyardsCliAT154 < Formula
  desc "Command-line interface for Backyards"
  homepage "https://banzaicloud.com/"
  version "1.5.4"
  bottle :unneeded

  if OS.mac?
    url "https://banzaicloud.com/downloads/backyards-cli/1.5.4/dist/backyards_1.5.4_darwin_amd64.tar.gz"
    sha256 "e02e564b26e3e4bb056238635da282f8b5ec1eae69e078f997a345bd5ed366a0"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://banzaicloud.com/downloads/backyards-cli/1.5.4/dist/backyards_1.5.4_linux_amd64.tar.gz"
      sha256 "8b66ed1353b9e9d8f330871ac0d5b7f2cbe8295a58540d4a93889b67f960363b"
    end
  end

  def install
    bin.install "backyards"
  end

  test do
    system "#{bin}/backyards --version"
  end
end
