# This file was generated by GoReleaser. DO NOT EDIT.
class BackyardsCliAT151 < Formula
  desc "Command-line interface for Backyards"
  homepage "https://banzaicloud.com/"
  version "1.5.1"
  bottle :unneeded

  if OS.mac?
    url "https://banzaicloud.com/downloads/backyards-cli/1.5.1/dist/backyards_1.5.1_darwin_amd64.tar.gz"
    sha256 "13fdde3574da3f417f1ccbc55076950fbb1fcc3cd7694d8c309e55c297fc27b8"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://banzaicloud.com/downloads/backyards-cli/1.5.1/dist/backyards_1.5.1_linux_amd64.tar.gz"
      sha256 "3c5159b3ed33a09780ad20711d17d2dfc57841301e47bd600b942b5213371a88"
    end
  end

  def install
    bin.install "backyards"
  end

  test do
    system "#{bin}/backyards --version"
  end
end
