# This file was generated by GoReleaser. DO NOT EDIT.
class BackyardsCliAT152 < Formula
  desc "Command-line interface for Backyards"
  homepage "https://banzaicloud.com/"
  version "1.5.2"
  bottle :unneeded

  if OS.mac?
    url "https://banzaicloud.com/downloads/backyards-cli/1.5.2/dist/backyards_1.5.2_darwin_amd64.tar.gz"
    sha256 "b5001abe75cb33f19e7272a99e7a93701b855d46ae23e52162534e8f38d05eaa"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://banzaicloud.com/downloads/backyards-cli/1.5.2/dist/backyards_1.5.2_linux_amd64.tar.gz"
      sha256 "0e641e0f2ec52bd8ad4b3e73123cb0d838f078ab1f916908dfdedc4c1f1b99ea"
    end
  end

  def install
    bin.install "backyards"
  end

  test do
    system "#{bin}/backyards --version"
  end
end
