# This file was generated by GoReleaser. DO NOT EDIT.
class BackyardsCliAT1410 < Formula
  desc "Command-line interface for Backyards"
  homepage "https://banzaicloud.com/"
  version "1.4.10"
  bottle :unneeded

  if OS.mac?
    url "https://banzaicloud.com/downloads/backyards-cli/1.4.10/dist/backyards_1.4.10_darwin_amd64.tar.gz"
    sha256 "cc8282da3cf17586fb0c219e924898540da8bf3f44696addb5b6d92f7400da39"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://banzaicloud.com/downloads/backyards-cli/1.4.10/dist/backyards_1.4.10_linux_amd64.tar.gz"
      sha256 "0d655ef945f39b1dda02190e4becaa9e053b850a0306e07b9886e5b7653488cd"
    end
  end

  def install
    bin.install "backyards"
  end

  test do
    system "#{bin}/backyards --version"
  end
end
