# This file was generated by GoReleaser. DO NOT EDIT.
class BanzaiCli < Formula
  desc "Command-line interface for Banzai Cloud Pipeline platform"
  homepage "https://banzaicloud.com/"
  version "0.19.0"

  if OS.mac?
    url "https://github.com/banzaicloud/banzai-cli/releases/download/0.19.0/banzai_0.19.0_darwin_amd64.tar.gz"
    sha256 "9ffc9404bdf792f692a9510ea66ef64eac7a0e1cab43d23b7bd2682ca0402156"
  elsif OS.linux?
    url "https://github.com/banzaicloud/banzai-cli/releases/download/0.19.0/banzai_0.19.0_linux_amd64.tar.gz"
    sha256 "41d526d98473fcf7d30596225b277b8db9e9fd436865c412752c0813b67e71ff"
  end
  
  depends_on "kubectl"

  def install
    bin.install "banzai"
    
    # Install bash completion
    output = Utils.popen_read("#{bin}/banzai completion bash")
    (bash_completion/"banzai").write output
    
    # Install zsh completion
    output = Utils.popen_read("#{bin}/banzai completion zsh")
    (zsh_completion/"_banzai").write output
  end

  test do
    system "#{bin}/banzai --version"
  end
end
