# This file was generated by GoReleaser. DO NOT EDIT.
class SupertubesCliAT070 < Formula
  desc "Command-line interface for Supertubes"
  homepage "https://banzaicloud.com/"
  version "0.7.0"
  bottle :unneeded

  if OS.mac?
    url "https://banzaicloud.com/downloads/supertubes-cli/0.7.0/dist/supertubes_0.7.0_darwin_amd64.tar.gz"
    sha256 "8477b67d6348adb7c4232d2e28d2538c030e7523c228f0082b8bd97970136fc8"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://banzaicloud.com/downloads/supertubes-cli/0.7.0/dist/supertubes_0.7.0_linux_amd64.tar.gz"
      sha256 "a7860d6acb8596c7d1145373aed1e6fdb36e8e930e701408c6f4cce505cf21b1"
    end
  end

  def install
    bin.install "supertubes"
  end

  test do
    system "#{bin}/supertubes --version"
  end
end
