# This file was generated by GoReleaser. DO NOT EDIT.
class SupertubesCliAT052 < Formula
  desc "Command-line interface for Supertubes"
  homepage "https://banzaicloud.com/"
  version "0.5.2"

  if OS.mac?
    url "https://banzaicloud.com/downloads/supertubes-cli/0.5.2/dist/supertubes_0.5.2_darwin_amd64.tar.gz"
    sha256 "b37d33b6ba9fd398f5644c69109fcd40569b9acbf9bbc001010846ff3d8016de"
  elsif OS.linux?
    url "https://banzaicloud.com/downloads/supertubes-cli/0.5.2/dist/supertubes_0.5.2_linux_amd64.tar.gz"
    sha256 "0937262e177e0e9f638694fe8112d7728329e2eb39ed3adc7a1b322ed025c4cf"
  end

  def install
    bin.install "supertubes"
  end

  test do
    system "#{bin}/supertubes --version"
  end
end
