# This file was generated by GoReleaser. DO NOT EDIT.
class SupertubesCliAT061 < Formula
  desc "Command-line interface for Supertubes"
  homepage "https://banzaicloud.com/"
  version "0.6.1"
  bottle :unneeded

  if OS.mac?
    url "https://banzaicloud.com/downloads/supertubes-cli/0.6.1/dist/supertubes_0.6.1_darwin_amd64.tar.gz"
    sha256 "bcc57bad03e39dc4b4b99d1bcdee4616b48b282f4cef3eebdd7abbf236b87e5b"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://banzaicloud.com/downloads/supertubes-cli/0.6.1/dist/supertubes_0.6.1_linux_amd64.tar.gz"
      sha256 "8719480bc7b37f9fbb49d991d7ad53071ab7d314367d6da1389c1edf30ad8e3d"
    end
  end

  def install
    bin.install "supertubes"
  end

  test do
    system "#{bin}/supertubes --version"
  end
end
