# This file was generated by GoReleaser. DO NOT EDIT.
class SupertubesCli < Formula
  desc "Command-line interface for Supertubes"
  homepage "https://banzaicloud.com/"
  version "1.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://banzaicloud.com/downloads/supertubes-cli/1.1.0/dist/supertubes_1.1.0_darwin_amd64.tar.gz"
    sha256 "51cfdddf0c1df01090c561d02196d0062ac92afac3e7f37e8427f3d01d64e8dd"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://banzaicloud.com/downloads/supertubes-cli/1.1.0/dist/supertubes_1.1.0_linux_amd64.tar.gz"
      sha256 "7233c47a5c65f9b49bea8b62ab1fd5332c4dd4c1640166bcfb5ad0acd46aea35"
    end
  end

  def install
    bin.install "supertubes"
  end

  test do
    system "#{bin}/supertubes --version"
  end
end
