# This file was generated by GoReleaser. DO NOT EDIT.
class SupertubesCliAT071 < Formula
  desc "Command-line interface for Supertubes"
  homepage "https://banzaicloud.com/"
  version "0.7.1"
  bottle :unneeded

  if OS.mac?
    url "https://banzaicloud.com/downloads/supertubes-cli/0.7.1/dist/supertubes_0.7.1_darwin_amd64.tar.gz"
    sha256 "889c0966f28d2235e0e5ca1acf9114f87e8b27db0e733cb3a734ae8d9e5cfab9"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://banzaicloud.com/downloads/supertubes-cli/0.7.1/dist/supertubes_0.7.1_linux_amd64.tar.gz"
      sha256 "55afd02d27be39c60774f501739a950683bd6cfb13af5a289cea894c5e83f8b3"
    end
  end

  def install
    bin.install "supertubes"
  end

  test do
    system "#{bin}/supertubes --version"
  end
end
