# This file was generated by GoReleaser. DO NOT EDIT.
class SupertubesCliAT100 < Formula
  desc "Command-line interface for Supertubes"
  homepage "https://banzaicloud.com/"
  version "1.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://banzaicloud.com/downloads/supertubes-cli/1.0.0/dist/supertubes_1.0.0_darwin_amd64.tar.gz"
    sha256 "3c64cf6da6412111355a6ecfa9d00f4e37b7c1f3d7855f28a0ccc3dd68f79828"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://banzaicloud.com/downloads/supertubes-cli/1.0.0/dist/supertubes_1.0.0_linux_amd64.tar.gz"
      sha256 "baa1a89065f943cc0afe3a99092c9b96f8b5b35b8b78574c734544a85bb75347"
    end
  end

  def install
    bin.install "supertubes"
  end

  test do
    system "#{bin}/supertubes --version"
  end
end
