# This file was generated by GoReleaser. DO NOT EDIT.
class TerraformProviderYami < Formula
  desc "Terraform provider with YAML deep merge capabilities"
  homepage "https://banzaicloud.com/"
  version "0.0.5"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/banzaicloud/terraform-provider-yami/releases/download/0.0.5/terraform-provider-yami_0.0.5_darwin_amd64.tar.gz"
    sha256 "33eb8909b72de27eaefd09a9dea540c639f74e0c179ce186c0a814a48e3e35d8"
  elsif OS.linux?
    url "https://github.com/banzaicloud/terraform-provider-yami/releases/download/0.0.5/terraform-provider-yami_0.0.5_linux_amd64.tar.gz"
    sha256 "67a1504a21a889c986c0fc2c69b75406d837d160e7961726f722bba7202fc490"
  end

  def install
    bin.install "terraform-provider-yami"
  end
end
