# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TerraformProviderK8s < Formula
  desc "Kubernetes Terraform provider with support for raw manifests"
  homepage "https://banzaicloud.com/"
  version "0.9.1"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/banzaicloud/terraform-provider-k8s/releases/download/v0.9.1/terraform-provider-k8s_0.9.1_darwin_amd64.zip"
    sha256 "991f1abe91c5e85d7056a40269a3ede16ea574f7d660f60276a21465f64f564d"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/banzaicloud/terraform-provider-k8s/releases/download/v0.9.1/terraform-provider-k8s_0.9.1_darwin_arm64.zip"
    sha256 "64a2bf297b838f139acf287690e8732e74285cacaac464f99b4bf47d8239d527"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/banzaicloud/terraform-provider-k8s/releases/download/v0.9.1/terraform-provider-k8s_0.9.1_linux_amd64.zip"
    sha256 "25d52b945a895a06a33756f77bfc28f1297bdece01193dcd94f780dc7ba5622a"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/banzaicloud/terraform-provider-k8s/releases/download/v0.9.1/terraform-provider-k8s_0.9.1_linux_arm.zip"
    sha256 "2fafff1df61205ab025e7c97a703c77091b68e739bc43df1043b6ca56bfea54d"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/banzaicloud/terraform-provider-k8s/releases/download/v0.9.1/terraform-provider-k8s_0.9.1_linux_arm64.zip"
    sha256 "ff204d13e191a65c37a357f28e623e02c132ae26a8c1939acf1a4bf6177ae892"
  end

  def install
    bin.install "terraform-provider-k8s"
  end
end
