# This file was generated by GoReleaser. DO NOT EDIT.
class Yami < Formula
  desc "YAML CLI merge tool"
  homepage "https://banzaicloud.com/"
  version "0.0.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/banzaicloud/yami/releases/download/0.0.4/yami_0.0.4_darwin_amd64.tar.gz"
    sha256 "fcdb8aae6f300fdf0a45a83551d305c377ef06f646b8dbbf4aa712161ee05249"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/banzaicloud/yami/releases/download/0.0.4/yami_0.0.4_linux_amd64.tar.gz"
      sha256 "be911f5eaace5b0d433bfcc75f1c5f89de24e15ea231ff91dc91ea51c6358273"
    end
  end

  def install
    bin.install "yami"
  end
end
